export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';


export const FETCH_CATEGORY_DETAILS_REQUEST = 'FETCH_CATEGORY_DETAILS_REQUEST';
export const FETCH_CATEGORY_DETAILS_SUCCESS = 'FETCH_CATEGORY_DETAILS_SUCCESS';
export const FETCH_CATEGORY_DETAILS_FAILURE = 'FETCH_CATEGORY_DETAILS_FAILURE';
